apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    type: reactnode
spec:
  containers:
  - name: odoo-container
    image: assc/odoo:latest
    ports:
      - name: odoo-container
        containerPort: 8069
        targetPort: 80
  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: rs
spec:
  replicas: 2
  template:
    metadata:
      name: my-pod
      labels:
        type: reactnode
    spec:
        containers:
        - name: odoo-container
          image: assc/odoo:latest
          ports:
            - name: odoo-container
              containerPort: 8069
              targetPort: 80
#gere les objet nouvellement cree 
  selector:
    matchLabels:
      type: reactnode 
      ---

apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  ports:
#port of container inside pod
  - targetPort: 8069
#port de service prend flux 3000 redirection vers port du pod
    port: 80
#port phy 3ibaratan map 3000 redirger vers port du service 80
    nodePort: 30000
#ya3ref les pods ili na7ki a3lihom ->label pod
  selector:
    type: reactnode
      
