apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo3
  template:
    metadata:
      labels:
        app: odoo3
    spec:
      containers:
      - name: odoo3
        image: odoo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: odoo3
  labels:
    app: odoo3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: odoo3
